---
- name: install git
  yum: name=git state=installed

- name: install apache php
  yum: name={{ item }} state=present
  with_items: 
    - httpd
    - php

- name: http service start
  service: 
    name: httpd
    state: started
    enabled: yes
